# Cache the Maven dependencies installed.
cache:
  directories:
  - $HOME/.m2

matrix:
   include:
      #      - os: osx
      #        install: ./.travis/install.sh
      #        script: ./.travis/build.sh
      - os: linux
        dist: trusty
        addons:
           apt:
              packages:
                 - oracle-java8-installer
        sudo: true
        install: ./.travis/install.sh
        script: ./.travis/build.sh

# Delete the batfish jars, which change every build, from the cache. Otherwise
# the cache would be detected as updated every time.
before_cache:
  - rm -rf $HOME/.m2/repository/org/batfish
