matrix:
   include:
      - os: linux
        dist: trusty
        language: java
        jdk:
          - oraclejdk8
        sudo: true
        install: ./.travis/install.sh
        script: ./.travis/build.sh

