matrix:
   include:
      - os: linux
        dist: trusty
        group: deprecated
        addons:
           apt:
              packages:
                 - oracle-java8-installer
        sudo: true
        install: ./.travis/install.sh
        script: ./.travis/build.sh

