language: java
jdk:
  - oraclejdk8
addons:
   hostname: short-hostname
matrix:
   include:
      - os: linux
        sudo: true
        dist: trusty
install: ./.travis/install.sh
script: ./.travis/build.sh

